[package]
name = "Programming-Assignment-1"
version = "0.1.0"
edition = "2021"

[dependencies]
confy = "0.6.1"
serde_derive = "1.0.217"
serde = { version = "1.0", features = ["derive"] }
tabled = "0.17.0"
